service:
  name: registry
  type: NodePort
  port: 5000
  nodePort: 10000

persistence:
  enabled: true
  size: 20Gi
  deleteEnabled: true
  existingClaim: docker-registry-pv-claim
secrets:
  htpasswd: admin:$2y$05$RDfDeRZ1qaKInE0CmY0k7OiBc.73C4godWqRVmHi07ALnlBWIO26m
