apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-share-dag-pv
  namespace: airflow
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  local:
    path: VOLUME_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - HOSTNAME_DNS

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-share-dag-pvc
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

