apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  namespace: jupyterhub
  labels:
    component: hub
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - HOSTNAME_DNS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-pv
  namespace: jupyterhub
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  local:
    path: VOLUME_PATH
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - HOSTNAME_DNS

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-share-pvc
  namespace: jupyterhub
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi

